### PR TITLE
add readme.md for profile

### PR DESCRIPTION
**Pull request by dvdmon**
Hello, just adding a readme for myself.  Not exactly sure if I did this exactly as you would expect.  Basically I forked the repo, cloned it, created a new branch, then pushed it back to my forked version.  Now I'm creating a pull request, intending it to be merged back into main.  But did I do that right or do I need to merge it into my main first and then create a pull request?  Sorry, this the first time I'm really collaborating on a project in Github!

### CODE REVIEW

**Comment by jjaimealeman** [comment]
@dvdmon 
Glad to see you here.
Give me a quick minute to Merge, and we should be all set ! :+1:

**Comment by dvdmon** [comment]
Cool, thanks @jjaimealeman! So did I do everything in the right way?

**Comment by jjaimealeman** [comment]
YES,
Ya did it right. You followed the right procedures for making a PR.

But make a folder with your name and put that readme in there.
Do another PR and I'll take it from there.

**Comment by dvdmon** [comment]
Hmmm, I did create a folder but damn, I put the readme file in the parent folder by mistake.  I'll move it and recommit

**Pull request merged**
