### PR TITLE
Trying to update again

### PR DESCRIPTION
**Pull request by dvdmon**
Somehow part of my file got removed last time, so had to resave it, and I also successfully moved it to the right folder and removed it from the parent folder.  Hopefully this does the trick.

### CODE REVIEW

**Comment by dvdmon** [comment]
So, from Colt's class, it seems like when you are done with a "feature" branch - when it's been merged back into main - often that extra branch is just removed because it's not going to be used again.  Is that how you do it?  If you removed the profileLW branch, and I fetched from your repository to my fork, it would be removed from mine as well, and if I did a pull it would be removed from my local as well, correct?  I generally don't remove feature branches at work, but I feel like maybe I should start as they are piling up quite a bit and I never go back to look at them after a release (or really after they are fully tested even before that...

**Comment by jjaimealeman** [comment]
>  Is that how you do it?

@dvdmon 

So far (from what I have noticed), when a PR comes in, I get the notification and proceed to inspect and make sure there are no Merge conflicts with existing files. 
As for the `profileLW` branch, that was auto-generated. As well as the other one for `add-code-of-conduct`. Not sure why?! None of the other merge/PRs created another branch, so I'm confused about that?!

But I believe that if I were to delete the branch from THIS repo, it should NOT affect yours. 

But what do I know? I'm still learning, lol.

Regarding the "Challenge", checkout https://jjaimealeman.github.io/wdb-get-good-with-git/ 
I thought it would be cool if everyone did their own thing and showed of something new they learned.
I'm playing with the Github and Twitter APIs and thought it would be neat to display my latest Tweet or info on the last commit - or something. Still learning ... we all are ;)

**Comment by dvdmon** [comment]
Cool. Do you want to try removing that branch and I'll let you know if it goes away from my fork when I fetch?

**Comment by jjaimealeman** [comment]
@dvdmon 
https://i.imgur.com/m5eDCoA.png

;) deleted.

Pretty cool. it gives me the option to RESTORE. Let me know if it's still there.

**Comment by dvdmon** [comment]
Will do - tomorrow (heading to bed) 👍

**Pull request merged**
