### PR TITLE
Form objects Article

### PR DESCRIPTION
**Pull request by aaron-watts**
New article added to aaron.html, and html syntax styling v1 added to syntax.js and syntax.css

### CODE REVIEW

**Comment by jjaimealeman** [comment]
I'm really liking that Typing Animation.

Would make a really nice Intro to show Git Newbs what commands to type, etc.

**Comment by aaron-watts** [comment]
I can pull the terminal css rules into their own file like I've done with the articles scripts if you like, so we can use them elsewhere without my any of my overrides messing any style rules up

**Comment by jjaimealeman** [comment]
@aaron-watts 

I had been thinking for a while now about how to best go about this _(non-important)_ Issue:

I was thinking of having a `global.css` and a `global.js`. Nothing drastic, but I would like a persistent nav bar on everyone's pages with a fixed position of `"0"` on everyone's page. Full `100vw` for responsiveness and various breakpoints if needed.
- I would like everyone to "Go Crazy" and style their own page as they like and use whatever API or `.js` they want, as you and Shakti have done.
- What about using the `<div id="container">` on everyone's pages?! Maintain a certain level of consistency? It can do without. As long as the navbar is there ;) But then again ... I don't want to restrict anyone to a certain screen width. Like I said, "Go Crazy".
- Your terminal CSS rules can possibly be applied through `@apply` in `global.css` so you don't have to maintain multiple versions of your file. It can just reference your CSS from the root, so you are free to make changes as needed.

---


These are just some late night ideas. It's 5:30 A.M. and I'm having trouble sleeping. Just wanted to post this real quick.

**Comment by aaron-watts** [comment]
> I was thinking of having a `global.css` and a `global.js`

I have already been treating your stylesheet as though it's global, I quite like your design choices on that. I always get choice paralysis when writing style sheets. I've only really overidden the container height really as my page is longer than the screen height.

It's worth logging an issue to discuss I think. I agree it would be good to have a consistent nav at the least.

I had to google `@apply`, I had never heard of it. I think you ought to give me some CSS lessons at some point!

**Pull request merged**
